# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('belt_app', '0002_auto_20170729_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokes_made', to='belt_app.User')),
                ('poki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokes_received', to='belt_app.User')),
            ],
        ),
    ]
